### ISSUE TITLE
bug: Illegally accessing dict

### ISSUE THREAD

**Issue by andreasoie** [TDT4265-tutorial/TDT4265_StarterCode#6]
Illegally accessing dict as member not index to a container (?)

See [this](https://github.com/TDT4265-tutorial/TDT4265_StarterCode/blob/164ef58c13b4eb9ccd891b81562c33c0bdf23257/assignment4/SSD/configs/tdt4265.py#L12) line as an example.
```python
train.imshape = (128, 1024) # raises AttributeError

train["imshape"] = (128, 1024)
```
Happens a few other places.

**Comment by hukkelas** [comment]
The access syntax is supported with the config parsing system that we use. Closing the issue for now.
